import { Edit3, Eye, Power, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { formatRecordDate, formatTargetValue, targetStatusLabels, targetTypeLabels, getRecordStatusVariant } from '../../utils/targetMapper'
import ProgressBar from '../ui/ProgressBar'
import Badge from '../ui/Badge'

function TargetTable({ records, onToggleStatus, onDelete }) {
  return (
    <>
      <div className="hidden overflow-hidden rounded-[2rem] border border-beige bg-white shadow-soft lg:block"><table className="w-full text-left text-sm"><thead className="bg-ivory text-xs font-semibold uppercase tracking-[0.18em] text-stone-400"><tr><th className="px-5 py-4">Employee</th><th className="px-5 py-4">Target</th><th className="px-5 py-4">Achieved</th><th className="px-5 py-4">Progress</th><th className="px-5 py-4">Period</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-beige">{records.map((record) => <tr key={record.id} className="transition hover:bg-ivory/70"><td className="px-5 py-4"><Link to={`/targets/${record.id}`} className="font-semibold text-charcoal transition hover:text-terracotta">{record.employee_name || 'Employee'}</Link><p className="mt-1 text-xs font-semibold text-brown">{record.employee_code}</p></td><td className="px-5 py-4 text-stone-600"><span className="font-semibold text-charcoal">{formatTargetValue(record)}</span><span className="mt-1 block text-xs text-stone-500">{targetTypeLabels[record.target_type]}</span></td><td className="px-5 py-4 text-stone-600">{formatTargetValue(record.target_type, record.achieved_value)}</td><td className="px-5 py-4"><ProgressBar value={record.progress_percentage} /></td><td className="px-5 py-4 text-stone-600">{formatRecordDate(record.start_date)} – {formatRecordDate(record.end_date)}</td><td className="px-5 py-4"><Badge variant={getRecordStatusVariant(record.status)}>{targetStatusLabels[record.status] || 'Unknown'}</Badge></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Link to={`/targets/${record.id}`} className="rounded-xl p-2 text-stone-500 transition hover:bg-cream hover:text-brown"><Eye className="h-4 w-4" /></Link><Link to={`/targets/${record.id}/edit`} className="rounded-xl p-2 text-stone-500 transition hover:bg-cream hover:text-brown"><Edit3 className="h-4 w-4" /></Link><button type="button" onClick={() => onToggleStatus(record)} className="rounded-xl p-2 text-stone-500 transition hover:bg-cream hover:text-brown"><Power className="h-4 w-4" /></button><button type="button" onClick={() => onDelete(record)} className="rounded-xl p-2 text-rose-muted transition hover:bg-rose-muted/10"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div>
      <div className="grid gap-4 lg:hidden">{records.map((record) => <article key={record.id} className="rounded-[2rem] border border-beige bg-white p-5 shadow-soft"><div className="flex justify-between gap-4"><div><Link to={`/targets/${record.id}`} className="text-lg font-semibold text-charcoal">{record.employee_name || 'Employee'}</Link><p className="mt-1 text-sm text-stone-500">{targetTypeLabels[record.target_type]}</p></div><Badge variant={getRecordStatusVariant(record.status)}>{targetStatusLabels[record.status] || 'Unknown'}</Badge></div><p className="mt-4 text-2xl font-semibold text-charcoal">{formatTargetValue(record)}</p><ProgressBar value={record.progress_percentage} label="Progress" className="mt-4" /><p className="mt-3 text-sm text-stone-500">{formatRecordDate(record.start_date)} – {formatRecordDate(record.end_date)}</p><div className="mt-5 grid grid-cols-4 gap-2"><Link to={`/targets/${record.id}`} className="inline-flex min-h-10 items-center justify-center rounded-2xl border border-beige bg-ivory text-brown"><Eye className="h-4 w-4" /></Link><Link to={`/targets/${record.id}/edit`} className="inline-flex min-h-10 items-center justify-center rounded-2xl border border-beige bg-ivory text-brown"><Edit3 className="h-4 w-4" /></Link><button type="button" onClick={() => onToggleStatus(record)} className="inline-flex min-h-10 items-center justify-center rounded-2xl border border-beige bg-ivory text-brown"><Power className="h-4 w-4" /></button><button type="button" onClick={() => onDelete(record)} className="inline-flex min-h-10 items-center justify-center rounded-2xl border border-rose-muted/30 bg-rose-muted/10 text-rose-muted"><Trash2 className="h-4 w-4" /></button></div></article>)}</div>
    </>
  )
}

export default TargetTable
